from django.utils.datastructures import SortedDict
from django.utils.translation import ugettext_lazy as _
from django.utils.encoding import force_unicode

# FIXME, handle separators in serverlist
# FIXME, move all this columns stuff out of config.py!

filters = [
    {'name': 'VLan/subnet', 'id': 'subnet'},
    {'name': 'Manual', 'id': 'manual',},
    ]

statusLevels = (
    ('1', _('1 - Critical')),
    ('2', _('2 - Production')),
    ('3', _('3 - Testing')),
    ('4', _('4 - Not installed')),
    ('5', _('5 - Autogenerated')),
    ('6', _('6 - Hidden')),
    )

statusLevelsDict = SortedDict(map(lambda x: (x[0], force_unicode(x[1])), statusLevels))

# Configuration which are dynamicly gathered and made available in the
# admin, DONT change this without knowing what you are doing.. Its
# internally used
Text = {
    'site': {'description': 'some description', 'default': 'default', 'permission': 'some permission'},
    'site2': {'description': 'some description4', 'default': 'some default4',},
    'site3': {'description': 'some description', 'default': 'some default1',},
    'site4': {'description': 'some description2', 'default': 'some default',},
    'usedColumns': {'description': 'List of used fields for server info (one per line), space separator for additional options (see documenation, FIXME).', 'default': 'aa\nbb',},
    }

# test with virtual not in config, and different ordering
